- name: add hhvm key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=0x5a16e7281be7a449 state=present
  when: ansible_distribution_version == '8'
  tags: hhvm

- name: add hhvm repo
  apt_repository: repo='deb http://dl.hhvm.com/debian jessie main' state=present
  when: ansible_distribution_version == '8'
  tags: hhvm

- name: Installing packages
  apt: pkg=hhvm update_cache=yes state=latest
  tags: hhvm
